# Generated by Django 4.2.5 on 2023-09-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_name', models.CharField(max_length=200)),
                ('current_day', models.DateField()),
                ('utc_time', models.DateTimeField()),
                ('track', models.CharField(max_length=200)),
            ],
        ),
    ]
