# Generated by Django 3.2.21 on 2023-09-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stackapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stack',
            new_name='Person',
        ),
    ]
